const firebaseConfig={apiKey:"AIzaSyBizGflMpcryMSGTNLdlhC1cDpq1cBM7Tk",authDomain:"pronostics-cdm2026-4f297.firebaseapp.com",projectId:"pronostics-cdm2026-4f297",storageBucket:"pronostics-cdm2026-4f297.firebasestorage.app",messagingSenderId:"178484979477",appId:"1:178484979477:web:34770c446003612d17ab1c"};
firebase.initializeApp(firebaseConfig);
const db=firebase.firestore();
const PL=[{id:'vadim',name:'Vadim',av:'V',ac:'av-v'},{id:'erwin',name:'Erwin',av:'E',ac:'av-e'},{id:'simon',name:'Simon',av:'S',ac:'av-s'},{id:'david',name:'David',av:'D',ac:'av-d'}];
let S={bankrolls:{vadim:50,erwin:50,simon:50,david:50},oublis:{vadim:0,erwin:0,simon:0,david:0}},paris=[];
const TD=()=>new Date().toISOString().slice(0,10),mm=br=>br<=0?0:Math.ceil(br*.2),gp=id=>PL.find(p=>p.id===id),eli=id=>S.bankrolls[id]<=0;
const tb=pid=>paris.filter(p=>p.playerId===pid&&p.date===TD()),hn=pid=>tb(pid).some(p=>!p.isSanction&&p.status==='pending'),hs=pid=>tb(pid).some(p=>p.isSanction&&p.status==='pending');
const sR=db.collection('game').doc('state'),pR=db.collection('paris');
async function init(){const s=await sR.get();if(!s.exists)await sR.set(S);}
sR.onSnapshot(s=>{if(s.exists){S=s.data();document.getElementById('syncDot').classList.add('live');ra();}});
pR.orderBy('createdAt','asc').onSnapshot(s=>{paris=s.docs.map(d=>({id:d.id,...d.data()}));ra();document.getElementById('loadingDash').style.display='none';document.getElementById('playerCards').style.display='grid';});
function ra(){rd();rp();rh();ps();}
function rd(){const sorted=[...PL].sort((a,b)=>S.bankrolls[b.id]-S.bankrolls[a.id]);let h='';sorted.forEach(p=>{const br=S.bankrolls[p.id],m=mm(br),el=eli(p.id),pct=Math.min(100,Math.max(0,(br/100)*100)),bc=el?'#E24B4A':br>=50?'#1D9E75':'#EF9F27',o=S.oublis[p.id];h+='<div class="pcard"><div class="pcard-head"><div class="av '+p.ac+'">'+p.av+'</div><div><div class="pname">'+p.name+(o>0?'<span class="oubli-badge">\xd7'+o+'</span>':'')+(hn(p.id)?'<span class="dot-today"></span>':'')+'</div><div class="pstatus">'+(el?'\xc9limin\xe9':hn(p.id)?'A pari\xe9':'En attente')+'</div></div></div><div class="br-row"><span class="br-label">Bankroll</span><span class="br-val">'+br.toFixed(2)+'\u20ac</span></div><div class="br-row"><span class="br-label">Mise min.</span><span class="mise-pill">'+(el?'\u2014':m+'\u20ac')+'</span></div><div class="bar-bg"><div class="bar-fg" style="width:'+pct+'%;background:'+bc+'"></div></div></div>';});document.getElementById('playerCards').innerHTML=h;const pend=paris.filter(p=>p.status==='pending');document.getElementById('pendingBanner').innerHTML=pend.length?'<div class="info-banner">'+pend.length+' pari(s) en attente \u2192 onglet <strong>Paris</strong></div>':'';}
function rp(){const pend=paris.filter(p=>p.status==='pending');if(!pend.length){document.getElementById('parisList').innerHTML='<div class="empty">Aucun pari en attente</div>';return;}let h='';pend.forEach(p=>{const pl=gp(p.playerId),gn=(p.mise*(p.cote-1)).toFixed(2);h+='<div class="pari-card"><div class="pari-top"><div class="pari-player"><div class="av '+pl.ac+'" style="width:22px;height:22px;font-size:10px">'+pl.av+'</div>'+pl.name+(p.isSanction?' <span class="chip chip-sanction">sanction</span>':'')+'</div><span class="pari-cote">'+p.mise+'\u20ac @ '+p.cote+'</span></div><div class="pari-desc">'+p.desc+'</div><div class="pari-gain">Gain net : +'+gn+'\u20ac</div>'+(p.isSanction&&p.sanctionnerId?'<div class="pari-sanction-info">Si gagn\xe9 \u2192 '+gp(p.sanctionnerId).name+' encaisse +'+gn+'\u20ac \xb7 '+pl.name+' r\xe9cup\xe8re 5\u20ac</div>':'')+'<div class="pari-actions"><button class="btn-sm btn-win" onclick="rP(\''+p.id+'\',\'won\')">\u2713 Gagn\xe9</button><button class="btn-sm btn-lose" onclick="rP(\''+p.id+'\',\'lost\')">\u2717 Perdu</button></div></div>';});document.getElementById('parisList').innerHTML=h;}
function rh(){const done=paris.filter(p=>p.status!=='pending').reverse();if(!done.length){document.getElementById('historiqueList').innerHTML='<div class="empty">Aucun r\xe9sultat encore</div>';return;}let h='';done.forEach(p=>{const pl=gp(p.playerId),gn=(p.mise*(p.cote-1)).toFixed(2);let d='',ex='';if(p.isSanction){if(p.status==='won'){d='Mise r\xe9cup\xe9r\xe9e';ex='<div class="hist-delta" style="color:var(--success);font-size:11px">'+(gp(p.sanctionnerId)||{}).name+' +'+gn+'\u20ac</div>';}else d='-5\u20ac';}else d=p.status==='won'?'+'+gn+'\u20ac':'-'+p.mise+'\u20ac';h+='<div class="hist-row"><div class="hist-left"><div class="hist-name">'+pl.name+(p.isSanction?' <span class="chip chip-sanction">sanction</span>':'')+'</div><div class="hist-detail">'+p.desc+' \xb7 '+p.mise+'\u20ac @ '+p.cote+'</div></div><div class="hist-right"><span class="chip '+(p.status==='won'?'chip-won':'chip-lost')+'">'+(p.status==='won'?'Gagn\xe9':'Perdu')+'</span><div class="hist-delta" style="color:'+(p.status==='won'?'var(--success)':'var(--danger)')+'">'+d+'</div>'+ex+'</div></div>';});document.getElementById('historiqueList').innerHTML=h;}
function ps(){['s-player','s-oubli'].forEach(sid=>{const sel=document.getElementById(sid),cur=sel.value;sel.innerHTML='';PL.forEach(p=>{if(!eli(p.id)){const o=document.createElement('option');o.value=p.id;o.textContent=p.name;sel.appendChild(o);}});if(cur)sel.value=cur;});umi();}
function umi(){const pid=document.getElementById('s-player').value;if(!pid)return;const br=S.bankrolls[pid];document.getElementById('s-miseinfo').textContent='BR : '+br.toFixed(2)+'\u20ac \u2014 mise min : '+mm(br)+'\u20ac';const is=document.getElementById('s-sanction').checked,ab=document.getElementById('s-alreadybet');if(hn(pid)&&!is){ab.style.display='block';ab.textContent=gp(pid).name+' a d\xe9j\xe0 son ticket du jour.';}else ab.style.display='none';}
function onPlayerChange(){umi();updateCoteInfo();const pid=document.getElementById('s-player').value;if(document.getElementById('s-sanction').checked)pSn(pid);}
function onSanctionChange(){const is=document.getElementById('s-sanction').checked;document.getElementById('s-sanctionner-group').style.display=is?'block':'none';document.getElementById('s-mise-group').style.opacity=is?'0.4':'1';const pid=document.getElementById('s-player').value;if(is&&pid)pSn(pid);umi();updateCoteInfo();}
function updateCoteInfo(){const is=document.getElementById('s-sanction').checked,cote=parseFloat(document.getElementById('s-cote').value),info=document.getElementById('s-coteinfo');if(!is||isNaN(cote)||cote<=1){info.style.display='none';return;}info.style.display='block';info.textContent='Si gagn\xe9 \u2192 gain net transf\xe9r\xe9 : '+(5*(cote-1)).toFixed(2)+'\u20ac';}
function pSn(excl){const sel=document.getElementById('s-sanctionner');sel.innerHTML='';PL.forEach(p=>{if(p.id!==excl&&!eli(p.id)){const o=document.createElement('option');o.value=p.id;o.textContent=p.name;sel.appendChild(o);}});}
async function declarerPari(){const pid=document.getElementById('s-player').value,desc=document.getElementById('s-desc').value.trim(),cote=parseFloat(document.getElementById('s-cote').value),is=document.getElementById('s-sanction').checked,mise=is?5:parseFloat(document.getElementById('s-mise').value),sId=is?document.getElementById('s-sanctionner').value:null,w=document.getElementById('s-warning');const sw=msg=>{w.style.display='block';w.textContent=msg;};w.style.display='none';if(!desc||isNaN(cote)||(isNaN(mise)&&!is)){sw('Merci de remplir tous les champs.');return;}if(cote<=1){sw('La cote doit \xeatre > 1.');return;}if(!is&&hn(pid)){sw(gp(pid).name+' a d\xe9j\xe0 un ticket normal aujourd\'hui.');return;}if(is&&hs(pid)){sw(gp(pid).name+' a d\xe9j\xe0 un ticket de sanction aujourd\'hui.');return;}const br=S.bankrolls[pid],m=mm(br);if(!is&&mise<m){sw('Mise trop faible. Minimum : '+m+'\u20ac');return;}if(mise>br){sw('Mise sup\xe9rieure \xe0 la bankroll.');return;}await sR.update({'bankrolls.'+pid:parseFloat((br-mise).toFixed(2))});await pR.add({playerId:pid,desc,cote,mise,isSanction:is,sanctionnerId:sId,status:'pending',date:TD(),createdAt:firebase.firestore.FieldValue.serverTimestamp()});document.getElementById('s-desc').value='';document.getElementById('s-cote').value='';document.getElementById('s-mise').value='';document.getElementById('s-sanction').checked=false;document.getElementById('s-sanctionner-group').style.display='none';document.getElementById('s-mise-group').style.opacity='1';document.getElementById('s-coteinfo').style.display='none';w.style.display='none';toast('Pari d\xe9clar\xe9 pour '+gp(pid).name+' !');}
async function rP(id,res){const p=paris.find(x=>x.id===id);if(!p)return;await pR.doc(id).update({status:res});if(p.isSanction){if(res==='won'){const gn=parseFloat((p.mise*(p.cote-1)).toFixed(2));await sR.update({'bankrolls.'+p.playerId:parseFloat((S.bankrolls[p.playerId]+p.mise).toFixed(2))});if(p.sanctionnerId){await sR.update({'bankrolls.'+p.sanctionnerId:parseFloat((S.bankrolls[p.sanctionnerId]+gn).toFixed(2))});toast('Gagn\xe9 ! '+gp(p.sanctionnerId).name+' encaisse +'+gn+'\u20ac');}}else toast('Perdu. '+gp(p.playerId).name+' perd 5\u20ac.');}else{if(res==='won'){const gn=parseFloat((p.mise*(p.cote-1)).toFixed(2));await sR.update({'bankrolls.'+p.playerId:parseFloat((S.bankrolls[p.playerId]+p.mise+gn).toFixed(2))});toast('Gagn\xe9 ! +'+gn+'\u20ac net');}else toast('Perdu.');}}
async function signalerOubli(){const pid=document.getElementById('s-oubli').value,player=gp(pid),nc=(S.oublis[pid]||0)+1;await sR.update({'oublis.'+pid:nc});const autres=PL.filter(p=>p.id!==pid&&!eli(p.id)),tirage=autres[Math.floor(Math.random()*autres.length)];document.getElementById('modal-title').textContent='Sanction \u2014 '+player.name;document.getElementById('modal-body').textContent='Oubli n\xb0'+nc+'. '+tirage.name+' est tir\xe9 au sort et choisit un pari de 5\u20ac pour '+player.name+'.';document.getElementById('modal-box').style.display='block';document.getElementById('modal-box').innerHTML='<div>\u2705 Si gagn\xe9 : '+player.name+' r\xe9cup\xe8re sa mise \xb7 '+tirage.name+' encaisse les gains nets</div><div>\u274c Si perdu : '+player.name+' perd 5\u20ac \xb7 '+tirage.name+' ne perd rien</div>';document.getElementById('modal').classList.add('open');}
function closeModal(){document.getElementById('modal').classList.remove('open');}
function switchTab(name){document.querySelectorAll('.tab').forEach((t,i)=>{const n=['dashboard','paris','saisir','historique'];t.classList.toggle('active',n[i]===name);});document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));document.getElementById('tab-'+name).classList.add('active');if(name==='saisir')ps();}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',2800);}
init();
